# Generated by Django 5.0.6 on 2026-06-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_resumedownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('image_url', models.URLField(blank=True, help_text='Optional profile image URL', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portfolio_testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
