# Generated by Django 5.0.6 on 2026-06-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_testimonial_contactinquiry_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'db_table': 'blog_categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('technologies', models.CharField(help_text='Comma-separated values', max_length=255)),
                ('features', models.TextField(help_text='Newline-separated values')),
                ('result', models.TextField()),
                ('github_link', models.URLField(blank=True, max_length=500, null=True)),
                ('live_link', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('django', 'Django'), ('php', 'PHP'), ('python', 'Python'), ('fullstack', 'Full Stack')], default='fullstack', max_length=50)),
                ('views_count', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Case Study',
                'verbose_name_plural': 'Project Case Studies',
                'db_table': 'project_case_studies',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'db_table': 'newsletter_subscribers',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=500)),
                ('content', models.TextField(help_text='Markdown content supported')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated values', max_length=255)),
                ('meta_description', models.CharField(blank=True, help_text='SEO Meta Description', max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='contacts.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
