# Generated by Django 5.0.6 on 2026-06-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_blogcategory_projectcasestudy_subscriber_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, default='', help_text='JSON metadata string')),
                ('is_qualified', models.BooleanField(default=False)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('scroll_depth', models.IntegerField(default=0)),
                ('time_on_site', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portfolio_leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
